In [5]:
using RCall
using LowRankApprox

In [2]:
include("../code/julia/mixSQP_time.jl")
include("../code/julia/REBayes.jl")
include("../code/julia/genL.jl")

genL (generic function with 1 method)

In [56]:
srand(1)
Z = randn(10,10^6) .* [1;1;1;1;1;5;5;10;10;20];
z = Z[:]; s = ones(5*10^6);

# example
L = genL(z[1:10^3],s[1:10^3], mult = 2.0);
[mixSQP_time(L)[4] REBayes(L)[2]];

In [60]:
L = genL(z[1:2^15],s[1:2^15], mult = 2.0);
println(size(L))
[mixSQP_time(L)[4] REBayes(L)[2]]

(32768, 13)


1×2 Array{Float64,2}:
 0.0774826  0.734

In [63]:
L = genL(z[1:2^16],s[1:2^16], mult = 1.4);
println(size(L))
[mixSQP_time(L)[4] REBayes(L)[2]]

(65536, 24)


1×2 Array{Float64,2}:
 0.213459  1.776

In [41]:
L = genL(z[1:2^20],s[1:2^20], mult = 1.2);
[mixSQP_time(L)[4] REBayes(L)[2]]

1×2 Array{Float64,2}:
 5.36741  97.762

In [42]:
size(L)

(1048576, 37)

In [31]:
t = zeros(5);
for i = 1:5
    n = 2^(10+2*i);
    L = genL(z[1:n],s[1:n], mult = 1.064)[:,1:100];
    tic();
    t[i] = mixSQP_time(L)[4];
    toc();
    println(t[i])
end

0.031823455
0.071620288
0.305306732
1.028306702
5.147090416


In [32]:
t = zeros(5);
for i = 1:5
    n = 2^(10+2*i);
    L = genL(z[1:n],s[1:n], mult = 1.031)[:,1:200];
    t[i] = mixSQP_time(L)[4];
    println(t[i])
end

0.063881406
0.17926826
0.361126117
1.184849378
5.2783076950000005
